# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5538a9977c5d07684a4aca6173e014f952173a1d5fb84f0ceed9860844fa7baa46723cc329b409c8610df5787ab62bbbc60b97204400260cccd4196cedfe510b

test:
  secret_key_base: 626cebeeff67c74ce4e152c279c4c2cbdf1cb64815320a8ec15b20360ac24745c93b5e7ea1b4a9fc1cda5bb0b623154ac2232a225e5a6f94745b74f494b2fd65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
